removed navbar item container. Added flex for svg container
keshav-bohr/google-homepage pull request #11
Opened 2021-06-17 16:23 UTC by keshav-bohr

2021-06-17 17:33 UTC, mkerney requested changes
Cross check if we need that property for sure or not.

2021-06-17 17:33 UTC, mkerney commented on src/components/navbar.scss
> +    height: 100%;
I don't think we need this.

2021-06-18 07:01 UTC, keshav-bohr commented on src/components/navbar.scss
> +    height: 100%;
Got it. Made the changes. Please check

2021-06-18 07:12 UTC, mkerney approved these changes

2021-06-18 07:21 UTC, merged